=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator/config/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Config (	GeneralSettings,
									MetaModelSettings,
								 	ProfiledModelSettings?,
								 	Transformations,
									Root,
								 	WhiteList,
									BlackList)>
<!ELEMENT GeneralSettings (	preventInconsistency,
													multiplicityPreconditions,
													reduceToSuperType,
													disableVariantsWithSupertypeReplacement,
													modelUsesProfileMechanism,
													createAllAttributes)>
<!ELEMENT MetaModelSettings (	 MainModel,
														 RequiredModel*,
														 Constraints?,
														 MaskedClassifiers?)>
<!ELEMENT ProfiledModelSettings (BaseModelRules)>
<!ELEMENT BaseModelRules EMPTY>
<!ELEMENT MainModel EMPTY>
<!ELEMENT RequiredModel EMPTY>
<!ELEMENT Constraints (NameUniqueness*) >
<!ELEMENT Mask EMPTY>
<!ELEMENT MaskedClassifiers (Mask*) >
<!ELEMENT NameUniqueness EMPTY>
<!ELEMENT Transformations (	Creates,
													Deletes,
													Moves,
													MoveUps,
													MoveDowns,
													SetAttributes,
													UnsetAttributes,
													SetReferences,
													UnsetReferences,
													Adds,
													Removes,
													ChangeLiterals,
													ChangeReferences)>
<!ELEMENT Root EMPTY>
<!ELEMENT BlackList (EClassifier*)>
<!ELEMENT WhiteList (EClassifier*)>

<!ELEMENT preventInconsistency EMPTY>
<!ELEMENT multiplicityPreconditions EMPTY>
<!ELEMENT reduceToSuperType EMPTY>
<!ELEMENT disableVariantsWithSupertypeReplacement EMPTY>
<!ELEMENT createAllAttributes EMPTY>
<!ELEMENT modelUsesProfileMechanism EMPTY>

<!ELEMENT Creates EMPTY>
<!ELEMENT Deletes EMPTY>
<!ELEMENT Moves EMPTY>
<!ELEMENT MoveDowns EMPTY>
<!ELEMENT MoveUps EMPTY>
<!ELEMENT SetAttributes EMPTY>
<!ELEMENT UnsetAttributes EMPTY>
<!ELEMENT SetReferences EMPTY>
<!ELEMENT UnsetReferences EMPTY>
<!ELEMENT Adds EMPTY>
<!ELEMENT Removes EMPTY>
<!ELEMENT ChangeLiterals EMPTY>
<!ELEMENT ChangeReferences EMPTY>

<!ELEMENT EClassifier EMPTY>
<!ATTLIST MainModel nsUri CDATA #REQUIRED>
<!ATTLIST RequiredModel nsUri CDATA #REQUIRED>
<!ATTLIST BaseModelRules path CDATA #REQUIRED>
<!ATTLIST NameUniqueness 
					scope CDATA #REQUIRED
					eClassifier CDATA #REQUIRED
					eAttributeName CDATA #REQUIRED
					eAttributeIsInherited  (true|false)  #REQUIRED
					overrideInheritedConstraintsIfAny  (true|false)  #REQUIRED
					applyOnSubTypes  (true|false)  #REQUIRED>
<!ATTLIST Mask 	name CDATA #REQUIRED
					eClassifier CDATA #REQUIRED
					eAttribute CDATA #REQUIRED
					eAttributeValue CDATA #REQUIRED>		
<!ATTLIST Root name CDATA #REQUIRED>
<!ATTLIST Root nested  (true|false)  #REQUIRED>
<!ATTLIST EClassifier name  (true|false)  #REQUIRED>
<!ATTLIST preventInconsistency value  (true|false)  #REQUIRED>
<!ATTLIST multiplicityPreconditions
					integrated  (true|false)  #REQUIRED
					separately  (true|false)  #REQUIRED>
<!ATTLIST disableVariantsWithSupertypeReplacement value  (true|false)  #REQUIRED>
<!ATTLIST createAllAttributes value  (true|false)  #REQUIRED>
<!ATTLIST modelUsesProfileMechanism value  (true|false)  #REQUIRED>

<!ATTLIST reduceToSuperType
					CREATE_DELETE  (true|false)  #REQUIRED
					MOVE  (true|false)  #REQUIRED
					MOVE_UP  (true|false)  #REQUIRED
					MOVE_DOWN  (true|false)  #REQUIRED
					SET_UNSET_ATTRIBUTE  (true|false)  #REQUIRED
					SET_UNSET_REFERENCE  (true|false)  #REQUIRED							
					ADD_REMOVE  (true|false)  #REQUIRED
					CHANGE_REFERENCE  (true|false)  #REQUIRED
					CHANGE_LITERAL  (true|false)  #REQUIRED>

<!ATTLIST Creates allow (true|false) #REQUIRED>
<!ATTLIST Deletes allow  (true|false)  #REQUIRED>
<!ATTLIST Moves allow  (true|false)  #REQUIRED
					allowReferenceSwitching  (true|false)  #REQUIRED
					allowReferenceCombinations  (true|false)  #REQUIRED>
<!ATTLIST MoveUps allow  (true|false)  #REQUIRED>
<!ATTLIST MoveDowns allow  (true|false)  #REQUIRED>
<!ATTLIST SetAttributes allow  (true|false)  #REQUIRED>
<!ATTLIST UnsetAttributes allow  (true|false)  #REQUIRED>
<!ATTLIST SetReferences allow  (true|false)  #REQUIRED>
<!ATTLIST UnsetReferences allow  (true|false)  #REQUIRED>
<!ATTLIST Adds allow  (true|false)  #REQUIRED>
<!ATTLIST Removes allow  (true|false)  #REQUIRED>
<!ATTLIST ChangeReferences allow  (true|false)  #REQUIRED>
<!ATTLIST ChangeLiterals allow  (true|false)  #REQUIRED
				  allowLiteralSwitching  (true|false)  #REQUIRED>

=== manuelohrndorf/sidiff-lifting/org.sidiff.serge/org.sidiff.serge/config/newExampleConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "config.dtd" >
<Config>
  <GeneralSettings>
    <preventInconsistency value="true"/>
    <multiplicityPreconditions integrated="true" separately="true"/>
    <reduceToSuperType ADD_REMOVE="true" CHANGE_LITERAL="true" CHANGE_REFERENCE="true" CREATE_DELETE="true" MOVE="true" MOVE_DOWN="true" MOVE_UP="true" SET_UNSET_ATTRIBUTE="true" SET_UNSET_REFERENCE="true"/>
    <disableVariants value="true"/>
    <modelUsesProfileMechanism value="true"/>
    <outputFolder absolutePath=""/>
    <createAllAttributes value="true"/>
  </GeneralSettings>
  <MetaModelSettings>
    <MainModel nsUri=""/>
  </MetaModelSettings>
  <Transformations>
    <Creates allow="true"/>
    <Deletes allow="true"/>
    <Moves allow="true" allowReferenceSwitching="true"/>
    <MoveUps allow="true" allowReferenceSwitching="true"/>
    <MoveDowns allow="true" allowReferenceSwitching="true"/>
    <SetAttributes allow="true"/>
    <UnsetAttributes allow="true"/>
    <SetReferences allow="true"/>
    <UnsetReferences allow="true"/>
    <Adds allow="true"/>
    <Removes allow="true"/>
    <ChangeLiterals allow="true" allowLiteralSwitching="true"/>
    <ChangeReferences allow="true"/>
  </Transformations>
  <Root name="" nested="true"/>
  <WhiteList/>
  <BlackList/>
</Config>
