=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/resources/org.sidiff.editrule.generator.serge.config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Config (MetaModel,
					Transformations,
					ConsistencyLevel,
					CompletnessLevel)>
					
<!ELEMENT MetaModel (MainModel,
						RequiredModel*,
					 	MaskedClassifiers?,
					 	RootModelElement?)>

<!ELEMENT MainModel EMPTY>
<!ATTLIST MainModel nsUri CDATA #REQUIRED
					isProfile (true|false) #IMPLIED>

<!ELEMENT RequiredModel EMPTY>
<!ATTLIST RequiredModel nsUri CDATA #REQUIRED>

<!ELEMENT MaskedClassifiers (Mask*) >	

<!ELEMENT Mask EMPTY>
<!ATTLIST Mask 	name CDATA #REQUIRED
					eClassifier CDATA #REQUIRED
					eAttribute CDATA #REQUIRED
					eAttributeValue CDATA #REQUIRED>

<!ELEMENT RootModelElement EMPTY>  <!-- TODO Must be optional -->
<!ATTLIST RootModelElement name CDATA #REQUIRED
			canBeNested  (true|false)  #REQUIRED>

<!ELEMENT Transformations (CREATE?,
							DELETE?,
							ATTACH?,
							DETACH?,
							MOVE?,
							MOVE_UP?,
							MOVE_DOWN?,
							SET_ATTRIBUTE?,
							UNSET_ATTRIBUTE?,
							SET_REFERENCE?,
							UNSET_REFERENCE?,
							ADD?,
							REMOVE?,
							CHANGE_LITERAL?,
							CHANGE_REFERENCE?)>	

<!ELEMENT CREATE EMPTY>
<!ATTLIST CREATE enable (true|false) #REQUIRED>
<!ELEMENT DELETE EMPTY>
<!ATTLIST DELETE enable (true|false) #REQUIRED>
<!ELEMENT ATTACH EMPTY>
<!ATTLIST ATTACH enable (true|false) #REQUIRED
					useSimpleNames (true|false)  #REQUIRED>
<!ELEMENT DETACH EMPTY>
<!ATTLIST DETACH enable (true|false) #REQUIRED>
<!ELEMENT MOVE EMPTY>
<!ATTLIST MOVE	enable (true|false) #REQUIRED
					allowReferenceSwitching  (true|false)  #REQUIRED
					allowReferenceCombinations  (true|false)  #REQUIRED>
<!ELEMENT MOVE_DOWN EMPTY>
<!ATTLIST MOVE_DOWN enable (true|false) #REQUIRED>
<!ELEMENT MOVE_UP EMPTY>
<!ATTLIST MOVE_UP enable (true|false) #REQUIRED>
<!ELEMENT SET_ATTRIBUTE EMPTY>
<!ATTLIST SET_ATTRIBUTE enable (true|false) #REQUIRED>
<!ELEMENT UNSET_ATTRIBUTE EMPTY>
<!ATTLIST UNSET_ATTRIBUTE enable (true|false) #REQUIRED>
<!ELEMENT SET_REFERENCE EMPTY>
<!ATTLIST SET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT UNSET_REFERENCE EMPTY>
<!ATTLIST UNSET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT ADD EMPTY>
<!ATTLIST ADD enable (true|false) #REQUIRED>
<!ELEMENT REMOVE EMPTY>
<!ATTLIST REMOVE enable (true|false) #REQUIRED>
<!ATTLIST SET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT CHANGE_LITERAL EMPTY>
<!ATTLIST CHANGE_LITERAL enable (true|false) #REQUIRED
							allowLiteralSwitching  (true|false)  #REQUIRED>
<!ELEMENT CHANGE_REFERENCE EMPTY>
<!ATTLIST CHANGE_REFERENCE enable (true|false) #REQUIRED>

<!ELEMENT ConsistencyLevel (CreateMandatoryChildren, CreateMandatoryNeighbours, CreateMultiplicityPreconditions)>		 	

<!ELEMENT CreateMandatoryChildren EMPTY>
<!ATTLIST CreateMandatoryChildren enable (true|false) #REQUIRED>

<!ELEMENT CreateMandatoryNeighbours EMPTY>
<!ATTLIST CreateMandatoryNeighbours enable (true|false) #REQUIRED>

<!ELEMENT CreateMultiplicityPreconditions EMPTY>
<!ATTLIST CreateMultiplicityPreconditions enable (true|false) #REQUIRED>
																
<!ELEMENT CompletnessLevel (AbstractReplacements, SupertypeReplacements, ModuleInternalOptions, ModuleSetOptions)>

<!ELEMENT AbstractReplacements (AbstractReplacement*)>

<!ELEMENT AbstractReplacement EMPTY>
<!ATTLIST AbstractReplacement ruleType (CREATE_DELETE | MOVE | MOVE_UP | MOVE_DOWN | SET_UNSET_ATTRIBUTE | SET_UNSET_REFERENCE | ADD_REMOVE | CHANGE_REFERENCE | CHANGE_LITERAL | ATTACH_DETACH) #REQUIRED
								reduceDanglings (true|false) #REQUIRED>

<!ELEMENT SupertypeReplacements (SupertypeReplacement*)>

<!ELEMENT SupertypeReplacement EMPTY>
<!ATTLIST SupertypeReplacement ruleType (CREATE_DELETE | MOVE | MOVE_UP | MOVE_DOWN | SET_UNSET_ATTRIBUTE | SET_UNSET_REFERENCE | ADD_REMOVE | CHANGE_REFERENCE | CHANGE_LITERAL | ATTACH_DETACH) #REQUIRED
								reduceDanglings (true|false) #REQUIRED
								reduceContext (true|false) #REQUIRED>
					
<!ELEMENT ModuleInternalOptions (CreateOptionalAttributes, DanglingNodeSettings)>

<!ELEMENT CreateOptionalAttributes EMPTY>
<!ATTLIST CreateOptionalAttributes enable (true|false) #REQUIRED>

<!ELEMENT DanglingNodeSettings (DanglingNodeSetting*)>
<!ATTLIST DanglingNodeSettings defaultTypeInclusion (never|ifRequired|always) #REQUIRED>

<!ELEMENT DanglingNodeSetting EMPTY>
<!ATTLIST DanglingNodeSetting type CDATA #REQUIRED
					include (never|ifRequired|always) #REQUIRED>


<!ELEMENT ModuleSetOptions (ModuleGenerationSettings)>

<!ELEMENT ModuleGenerationSettings (GenerateModulesFor*)>
<!ATTLIST ModuleGenerationSettings defaultGenerationCase (never|ifRequired|always) #REQUIRED>

<!ELEMENT GenerateModulesFor EMPTY>
<!-- "always" means all types (including indirectly required, "ifRequired" means only explicit as "always" marked types and their indirectly required types -->
<!ATTLIST GenerateModulesFor type CDATA #REQUIRED
					case (never|ifRequired|always) #REQUIRED>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/uml_classdiagram_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >

<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/uml2/4.0.0/UML"
			isProfile="false" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/Types" />
		<RequiredModel nsUri="http://www.eclipse.org/emf/2002/Ecore" />
		<RootModelElement name="Model" canBeNested="false" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="false" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="ifRequired">
							<DanglingNodeSetting type="Abstraction" include="always" />
				<DanglingNodeSetting type="Association" include="always" />
				<DanglingNodeSetting type="Class" include="always" />
				<DanglingNodeSetting type="Enumeration" include="always" />
				<DanglingNodeSetting type="EnumerationLiteral"
					include="always" />
				<DanglingNodeSetting type="Generalization" include="always" />
				<DanglingNodeSetting type="LiteralBoolean" include="always" />
				<DanglingNodeSetting type="LiteralString" include="always" />
				<DanglingNodeSetting type="Operation" include="always" />
				<DanglingNodeSetting type="Package" include="always" />
				<DanglingNodeSetting type="Parameter" include="always" />
				<DanglingNodeSetting type="Port" include="always" />
				<DanglingNodeSetting type="ProfileApplication"
					include="always" />
				<DanglingNodeSetting type="Property" include="always" />
				<DanglingNodeSetting type="Type" include="always" />
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="ifRequired">
				<GenerateModulesFor type="Abstraction" case="always" />
				<GenerateModulesFor type="Association" case="always" />
				<GenerateModulesFor type="Class" case="always" />
				<GenerateModulesFor type="Enumeration" case="always" />
				<GenerateModulesFor type="EnumerationLiteral"
					case="always" />
				<GenerateModulesFor type="Generalization" case="always" />
				<GenerateModulesFor type="LiteralBoolean" case="always" />
				<GenerateModulesFor type="LiteralString" case="always" />
				<GenerateModulesFor type="Operation" case="always" />
				<GenerateModulesFor type="Package" case="always" />
				<GenerateModulesFor type="Parameter" case="always" />
				<GenerateModulesFor type="Port" case="always" />
				<GenerateModulesFor type="ProfileApplication"
					case="always" />
				<GenerateModulesFor type="Property" case="always" />
				<GenerateModulesFor type="Type" case="always" />
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/new_untested/Henshin.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >

<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/emf/2011/Henshin" isProfile="false" />
		<RequiredModel nsUri="http://www.eclipse.org/emf/2002/Ecore" />	
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="true" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
		</AbstractReplacements>
		<SupertypeReplacements>
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="always">
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="always">
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>
