=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/resources/org.sidiff.editrule.generator.serge.config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Config (MetaModel,
					Transformations,
					ConsistencyLevel,
					CompletnessLevel)>
					
<!ELEMENT MetaModel (MainModel,
						RequiredModel*,
					 	MaskedClassifiers?,
					 	RootModelElement?)>

<!ELEMENT MainModel EMPTY>
<!ATTLIST MainModel nsUri CDATA #REQUIRED
					isProfile (true|false) #IMPLIED>

<!ELEMENT RequiredModel EMPTY>
<!ATTLIST RequiredModel nsUri CDATA #REQUIRED>

<!ELEMENT MaskedClassifiers (Mask*) >	

<!ELEMENT Mask EMPTY>
<!ATTLIST Mask 	name CDATA #REQUIRED
					eClassifier CDATA #REQUIRED
					eAttribute CDATA #REQUIRED
					eAttributeValue CDATA #REQUIRED>

<!ELEMENT RootModelElement EMPTY>  <!-- TODO Must be optional -->
<!ATTLIST RootModelElement name CDATA #REQUIRED
			canBeNested  (true|false)  #REQUIRED>

<!ELEMENT Transformations (CREATE?,
							DELETE?,
							ATTACH?,
							DETACH?,
							MOVE?,
							MOVE_UP?,
							MOVE_DOWN?,
							SET_ATTRIBUTE?,
							UNSET_ATTRIBUTE?,
							SET_REFERENCE?,
							UNSET_REFERENCE?,
							ADD?,
							REMOVE?,
							CHANGE_LITERAL?,
							CHANGE_REFERENCE?)>	

<!ELEMENT CREATE EMPTY>
<!ATTLIST CREATE enable (true|false) #REQUIRED>
<!ELEMENT DELETE EMPTY>
<!ATTLIST DELETE enable (true|false) #REQUIRED>
<!ELEMENT ATTACH EMPTY>
<!ATTLIST ATTACH enable (true|false) #REQUIRED
					useSimpleNames (true|false)  #REQUIRED>
<!ELEMENT DETACH EMPTY>
<!ATTLIST DETACH enable (true|false) #REQUIRED>
<!ELEMENT MOVE EMPTY>
<!ATTLIST MOVE	enable (true|false) #REQUIRED
					allowReferenceSwitching  (true|false)  #REQUIRED
					allowReferenceCombinations  (true|false)  #REQUIRED>
<!ELEMENT MOVE_DOWN EMPTY>
<!ATTLIST MOVE_DOWN enable (true|false) #REQUIRED>
<!ELEMENT MOVE_UP EMPTY>
<!ATTLIST MOVE_UP enable (true|false) #REQUIRED>
<!ELEMENT SET_ATTRIBUTE EMPTY>
<!ATTLIST SET_ATTRIBUTE enable (true|false) #REQUIRED>
<!ELEMENT UNSET_ATTRIBUTE EMPTY>
<!ATTLIST UNSET_ATTRIBUTE enable (true|false) #REQUIRED>
<!ELEMENT SET_REFERENCE EMPTY>
<!ATTLIST SET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT UNSET_REFERENCE EMPTY>
<!ATTLIST UNSET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT ADD EMPTY>
<!ATTLIST ADD enable (true|false) #REQUIRED>
<!ELEMENT REMOVE EMPTY>
<!ATTLIST REMOVE enable (true|false) #REQUIRED>
<!ATTLIST SET_REFERENCE enable (true|false) #REQUIRED>
<!ELEMENT CHANGE_LITERAL EMPTY>
<!ATTLIST CHANGE_LITERAL enable (true|false) #REQUIRED
							allowLiteralSwitching  (true|false)  #REQUIRED>
<!ELEMENT CHANGE_REFERENCE EMPTY>
<!ATTLIST CHANGE_REFERENCE enable (true|false) #REQUIRED>

<!ELEMENT ConsistencyLevel (CreateMandatoryChildren, CreateMandatoryNeighbours, CreateMultiplicityPreconditions)>		 	

<!ELEMENT CreateMandatoryChildren EMPTY>
<!ATTLIST CreateMandatoryChildren enable (true|false) #REQUIRED>

<!ELEMENT CreateMandatoryNeighbours EMPTY>
<!ATTLIST CreateMandatoryNeighbours enable (true|false) #REQUIRED>

<!ELEMENT CreateMultiplicityPreconditions EMPTY>
<!ATTLIST CreateMultiplicityPreconditions enable (true|false) #REQUIRED>
																
<!ELEMENT CompletnessLevel (AbstractReplacements, SupertypeReplacements, ModuleInternalOptions, ModuleSetOptions)>

<!ELEMENT AbstractReplacements (AbstractReplacement*)>

<!ELEMENT AbstractReplacement EMPTY>
<!ATTLIST AbstractReplacement ruleType (CREATE_DELETE | MOVE | MOVE_UP | MOVE_DOWN | SET_UNSET_ATTRIBUTE | SET_UNSET_REFERENCE | ADD_REMOVE | CHANGE_REFERENCE | CHANGE_LITERAL | ATTACH_DETACH) #REQUIRED
								reduceDanglings (true|false) #REQUIRED>

<!ELEMENT SupertypeReplacements (SupertypeReplacement*)>

<!ELEMENT SupertypeReplacement EMPTY>
<!ATTLIST SupertypeReplacement ruleType (CREATE_DELETE | MOVE | MOVE_UP | MOVE_DOWN | SET_UNSET_ATTRIBUTE | SET_UNSET_REFERENCE | ADD_REMOVE | CHANGE_REFERENCE | CHANGE_LITERAL | ATTACH_DETACH) #REQUIRED
								reduceDanglings (true|false) #REQUIRED
								reduceContext (true|false) #REQUIRED>
					
<!ELEMENT ModuleInternalOptions (CreateOptionalAttributes, DanglingNodeSettings)>

<!ELEMENT CreateOptionalAttributes EMPTY>
<!ATTLIST CreateOptionalAttributes enable (true|false) #REQUIRED>

<!ELEMENT DanglingNodeSettings (DanglingNodeSetting*)>
<!ATTLIST DanglingNodeSettings defaultTypeInclusion (never|ifRequired|always) #REQUIRED>

<!ELEMENT DanglingNodeSetting EMPTY>
<!ATTLIST DanglingNodeSetting type CDATA #REQUIRED
					include (never|ifRequired|always) #REQUIRED>


<!ELEMENT ModuleSetOptions (ModuleGenerationSettings)>

<!ELEMENT ModuleGenerationSettings (GenerateModulesFor*)>
<!ATTLIST ModuleGenerationSettings defaultGenerationCase (never|ifRequired|always) #REQUIRED>

<!ELEMENT GenerateModulesFor EMPTY>
<!-- "always" means all types (including indirectly required, "ifRequired" means only explicit as "always" marked types and their indirectly required types -->
<!ATTLIST GenerateModulesFor type CDATA #REQUIRED
					case (never|ifRequired|always) #REQUIRED>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/marte_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >
<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/papyrus/MARTE/1"
			isProfile="true" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/UML" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/Types" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<ATTACH enable="true" useSimpleNames="true" />
		<DETACH enable="true"/>
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="true" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ATTACH_DETACH"
				reduceDanglings="false" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ATTACH_DETACH"
				reduceDanglings="false" reduceContext="false" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="always">
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="ifRequired">
				<GenerateModulesFor type="RtUnit" case="always" />
				<GenerateModulesFor type="PpUnit" case="always" />
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/new_untested/sysml.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >

<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/papyrus/0.7.0/SysML" isProfile="false" />
		<RequiredModel nsUri="http://www.eclipse.org/emf/2002/Ecore" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/UML" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/Types" />
		<RootModelElement name="Model" canBeNested="false" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="false" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="ifRequired">
				<DanglingNodeSetting type="Block" include="always" />
				<DanglingNodeSetting type="FlowPort" include="always" />
				<DanglingNodeSetting type="ConstraintProperty"
					include="always" />
				<DanglingNodeSetting type="ConstraintBlock"
					include="always" />
				<DanglingNodeSetting type="RequirementRelated"
					include="always" />
				<DanglingNodeSetting type="Requirement" include="always" />
				<DanglingNodeSetting type="Satisfy" include="always" />
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="ifRequired">
				<GenerateModulesFor type="Block" case="always" />
				<GenerateModulesFor type="FlowPort" case="always" />
				<GenerateModulesFor type="ConstraintProperty"
					case="always" />
				<GenerateModulesFor type="ConstraintBlock"
					case="always" />
				<GenerateModulesFor type="RequirementRelated"
					case="always" />
				<GenerateModulesFor type="Requirement" case="always" />
				<GenerateModulesFor type="Satisfy" case="always" />
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/uml_sequencediagram_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >

<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/uml2/4.0.0/UML"
			isProfile="false" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/Types" />
		<RequiredModel nsUri="http://www.eclipse.org/emf/2002/Ecore" />
		<MaskedClassifiers>
			<Mask name="InitialPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="initial" />
			<Mask name="ChoicePseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="choice" />
			<Mask name="DeepHistoryPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="deepHistory" />
			<Mask name="ShallowHistoryPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="shallowHistory" />
			<Mask name="JoinPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="join" />
			<Mask name="ForkPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="fork" />
			<Mask name="JunctionPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="junction" />
			<Mask name="EntryPointPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="entryPoint" />
			<Mask name="ExitPointPseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="exitPoint" />
			<Mask name="TerminatePseudostate" eClassifier="Pseudostate"
				eAttribute="kind" eAttributeValue="terminate" />
		</MaskedClassifiers>
		<RootModelElement name="Model" canBeNested="true" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="true" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="ifRequired">
				<DanglingNodeSetting type="Interaction" include="always" />
				<DanglingNodeSetting type="InteractionFragment" include="always" />
				<DanglingNodeSetting type="ActionExecutionSpecification"
					include="always" />
				<DanglingNodeSetting type="BehaviorExecutionSpecification"
					include="always" />
				<DanglingNodeSetting type="CombinedFragment"
					include="always" />
				<DanglingNodeSetting type="ConsiderIgnoreFragment"
					include="always" />
				<DanglingNodeSetting type="Continuation"
					include="always" />
				<DanglingNodeSetting type="DurationConstraint"
					include="always" />
				<DanglingNodeSetting type="DurationObservation"
					include="always" />
				<DanglingNodeSetting type="Gate" include="always" />
				<DanglingNodeSetting type="InteractionOperand"
					include="always" />
				<DanglingNodeSetting type="InteractionUse"
					include="always" />
				<DanglingNodeSetting type="Lifeline" include="always" />
				<DanglingNodeSetting type="StateInvariant"
					include="always" />
				<DanglingNodeSetting type="TimeConstraint"
					include="always" />
				<DanglingNodeSetting type="TimeObservation"
					include="always" />
				<DanglingNodeSetting type="Message" include="always" />
				<DanglingNodeSetting type="MessageOccurrenceSpecification"
					include="always" />
				<DanglingNodeSetting type="MessageEnd" include="always" />
				<DanglingNodeSetting type="Event" include="always" />
				<DanglingNodeSetting type="AnyReceiveEvent"
					include="always" />
				<DanglingNodeSetting type="CallEvent" include="always" />
				<DanglingNodeSetting type="DestructionOccurrenceSpecification"
					include="always" />
				<DanglingNodeSetting type="SignalEvent" include="always" />
				<DanglingNodeSetting type="Constraint" include="always" />
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="ifRequired">
				<GenerateModulesFor type="Interaction" case="always" />
				<GenerateModulesFor type="InteractionFragment" case="always" />
				<GenerateModulesFor type="ActionExecutionSpecification"
					case="always" />
				<GenerateModulesFor type="BehaviorExecutionSpecification"
					case="always" />
				<GenerateModulesFor type="CombinedFragment" case="always" />
				<GenerateModulesFor type="ConsiderIgnoreFragment"
					case="always" />
				<GenerateModulesFor type="Continuation" case="always" />
				<GenerateModulesFor type="DurationConstraint"
					case="always" />
				<GenerateModulesFor type="DurationObservation"
					case="always" />
				<GenerateModulesFor type="Gate" case="always" />
				<GenerateModulesFor type="InteractionOperand"
					case="always" />
				<GenerateModulesFor type="InteractionUse" case="always" />
				<GenerateModulesFor type="Lifeline" case="always" />
				<GenerateModulesFor type="StateInvariant" case="always" />
				<GenerateModulesFor type="TimeConstraint" case="always" />
				<GenerateModulesFor type="TimeObservation" case="always" />
				<GenerateModulesFor type="Message" case="always" />
				<GenerateModulesFor type="MessageOccurrenceSpecification"
					case="always" />
				<GenerateModulesFor type="MessageEnd" case="always" />
				<GenerateModulesFor type="Event" case="always" />
				<GenerateModulesFor type="AnyReceiveEvent" case="always" />
				<GenerateModulesFor type="CallEvent" case="always" />
				<GenerateModulesFor type="DestructionOccurrenceSpecification"
					case="always" />
				<GenerateModulesFor type="SignalEvent" case="always" />
				<GenerateModulesFor type="Constraint" case="always" />
				<GenerateModulesFor type="ActionInputPin" case="never" />
				<GenerateModulesFor type="ValuePin" case="never" />
				<GenerateModulesFor type="InputPin" case="never" />
				<GenerateModulesFor type="Pin" case="never" />
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/ecore_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >
<!-- Based on org.sidiff.ecore.editrules.atomic/editrules/generated/usedConfig_20140828.serge -->
<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/emf/2002/Ecore"
			isProfile="false" />
		<RootModelElement name="EPackage" canBeNested="true" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="false"
			allowReferenceCombinations="false" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="false" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="true" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE" reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="false" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="false" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="always">
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings defaultGenerationCase="always">
				<GenerateModulesFor type="EFactory" case="never" />
				<GenerateModulesFor type="EGenericType"
					case="never" />
				<GenerateModulesFor type="EObject" case="never" />
				<!-- <GenerateModulesFor type="EStringToStringMapEntry"
					case="never" />  -->
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>

=== manuelohrndorf/sidiff-lifting/plugins/org.sidiff.editrule.generator.serge/config/classdiagram.config2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Config SYSTEM "org.sidiff.editrule.generator.serge.config.dtd" >

<Config>
	<MetaModel>
		<MainModel nsUri="http://www.eclipse.org/uml2/4.0.0/UML"
			isProfile="false" />
		<RequiredModel nsUri="http://www.eclipse.org/uml2/4.0.0/Types" />
		<RequiredModel nsUri="http://www.eclipse.org/emf/2002/Ecore" />
		<RootModelElement name="Model" canBeNested="false" />
	</MetaModel>

	<Transformations>
		<CREATE enable="true" />
		<DELETE enable="true" />
		<MOVE enable="true" allowReferenceSwitching="true"
			allowReferenceCombinations="true" />
		<MOVE_UP enable="true" />
		<MOVE_DOWN enable="true" />
		<SET_ATTRIBUTE enable="true" />
		<UNSET_ATTRIBUTE enable="true" />
		<SET_REFERENCE enable="true" />
		<UNSET_REFERENCE enable="true" />
		<ADD enable="true" />
		<REMOVE enable="true" />
		<CHANGE_LITERAL enable="true" allowLiteralSwitching="true" />
		<CHANGE_REFERENCE enable="true" />
	</Transformations>

	<ConsistencyLevel>
		<CreateMandatoryChildren enable="true" />
		<CreateMandatoryNeighbours enable="true" />
		<CreateMultiplicityPreconditions
			enable="false" />
	</ConsistencyLevel>

	<CompletnessLevel>
		<AbstractReplacements>
			<AbstractReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_UP"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" />
			<AbstractReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" />
		</AbstractReplacements>
		<SupertypeReplacements>
			<SupertypeReplacement ruleType="CREATE_DELETE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="ADD_REMOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_UP"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="MOVE_DOWN"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_ATTRIBUTE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="SET_UNSET_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_LITERAL"
				reduceDanglings="true" reduceContext="true" />
			<SupertypeReplacement ruleType="CHANGE_REFERENCE"
				reduceDanglings="true" reduceContext="true" />
		</SupertypeReplacements>

		<ModuleInternalOptions>
			<CreateOptionalAttributes enable="true" />
			<DanglingNodeSettings defaultTypeInclusion="ifRequired">
			</DanglingNodeSettings>
		</ModuleInternalOptions>

		<ModuleSetOptions>
			<ModuleGenerationSettings
				defaultGenerationCase="never">
				<GenerateModulesFor type="Property" case="always" />
				<GenerateModulesFor type="ExtensionEnd" case="never" />
				<GenerateModulesFor type="Port" case="never" />
			</ModuleGenerationSettings>
		</ModuleSetOptions>
	</CompletnessLevel>
</Config>
